name: CI

on:
  pull_request:
  push:
    branches: stable

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Version
      run: |
        sudo xcode-select --switch /Applications/Xcode_12.5.1.app
        xcode-select --print-path
        xcodebuild -version
    - name: Prerequisites
      run: |
        gem install xcpretty
    - name: Build
      run: |
        set -o pipefail
        xcodebuild -scheme Nio -destination 'platform=iOS Simulator,name=iPhone 12' build | xcpretty --color
    - name: Test
      run: |
        set -o pipefail
        xcodebuild -scheme Nio -destination 'platform=iOS Simulator,name=iPhone 12' test | xcpretty --color --test
